name: Docker Image CI

on:
  registry_package:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: env
    - run: "sed 's/.*\"version\": \"\\(.*\\)\".*/\\1/;t;d' ./package.json\""
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag meistr/reroute:$(date +%s)
#     - name: Tag latest
#       run: docker tag meistr/reroute:$() meistr/reroute:latest
