name: Docker Image CI

# on:
#   release:
#     types: [created]
on:
  # registry_package:
  #   types: [published]
  push:
    branches:
      - test-branch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v1
        with:
          username: meistr
          password: ${{ secrets.docker_hub_token }}
          repository: meistr/reroute
          tag_with_ref: true
