name: Docker Image CI

on:
  registry_package:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: meistr
          password: ${{ secrets.docker_hub_token }}
          repository: meistr/reroute
          tag_with_ref: true
          tags: latest
